In [1]:
import numpy as np

In [13]:
a = np.random.permutation(12).reshape((3,4))
a

array([[ 5,  0,  9,  4],
       [ 2,  8,  7, 10],
       [ 1, 11,  3,  6]])

In [14]:
np.exp(a)

array([[1.48413159e+02, 1.00000000e+00, 8.10308393e+03, 5.45981500e+01],
       [7.38905610e+00, 2.98095799e+03, 1.09663316e+03, 2.20264658e+04],
       [2.71828183e+00, 5.98741417e+04, 2.00855369e+01, 4.03428793e+02]])

In [15]:
np.sqrt(a)

array([[2.23606798, 0.        , 3.        , 2.        ],
       [1.41421356, 2.82842712, 2.64575131, 3.16227766],
       [1.        , 3.31662479, 1.73205081, 2.44948974]])

In [18]:
a = np.floor(10*np.random.random((3, 4)))
a

array([[6., 2., 2., 2.],
       [8., 8., 3., 2.],
       [6., 1., 2., 0.]])

In [19]:
a.ravel()

array([6., 2., 2., 2., 8., 8., 3., 2., 6., 1., 2., 0.])

In [20]:
a.flatten()

array([6., 2., 2., 2., 8., 8., 3., 2., 6., 1., 2., 0.])

In [21]:
a.shape = (6, 2)
a

array([[6., 2.],
       [2., 2.],
       [8., 8.],
       [3., 2.],
       [6., 1.],
       [2., 0.]])

In [22]:
a.T

array([[6., 2., 8., 3., 6., 2.],
       [2., 2., 8., 2., 1., 0.]])

In [27]:
a = np.floor(10*np.random.random((3, 4)))
b = np.floor(10*np.random.random((3, 4)))
print(a)
print(15*'-')
print(b)

[[6. 7. 6. 2.]
 [4. 5. 7. 6.]
 [1. 5. 0. 6.]]
---------------
[[4. 0. 5. 1.]
 [7. 4. 6. 2.]
 [2. 0. 0. 7.]]


In [29]:
np.hstack([a,b]) # column wise stack

array([[6., 7., 6., 2., 4., 0., 5., 1.],
       [4., 5., 7., 6., 7., 4., 6., 2.],
       [1., 5., 0., 6., 2., 0., 0., 7.]])

In [30]:
np.vstack([a,b]) # row wise stack

array([[6., 7., 6., 2.],
       [4., 5., 7., 6.],
       [1., 5., 0., 6.],
       [4., 0., 5., 1.],
       [7., 4., 6., 2.],
       [2., 0., 0., 7.]])

In [31]:
a = np.floor(10*np.random.random((3, 4)))
a

array([[4., 8., 8., 3.],
       [8., 4., 7., 3.],
       [8., 8., 2., 9.]])

In [34]:
np.hsplit(a, 2)

[array([[4., 8.],
        [8., 4.],
        [8., 8.]]), array([[8., 3.],
        [7., 3.],
        [2., 9.]])]

In [37]:
np.vsplit(a, 3)

[array([[4., 8., 8., 3.]]),
 array([[8., 4., 7., 3.]]),
 array([[8., 8., 2., 9.]])]

In [39]:
a = np.sin(np.arange(20).reshape((4,5)))
a

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [41]:
max_idx = a.argmax(axis=0) # column wise
max_idx

array([3, 0, 0, 1, 2])

In [46]:
a[max_idx, range(a.shape[1])]

array([0.65028784, 0.84147098, 0.90929743, 0.98935825, 0.99060736])

In [47]:
a.max(axis=0)

array([0.65028784, 0.84147098, 0.90929743, 0.98935825, 0.99060736])

In [49]:
a = np.arange(0, 40, 10)
a

array([ 0, 10, 20, 30])

In [53]:
np.tile(a, (2, 2))

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [57]:
a = np.random.random(10)

In [58]:
np.sort(a, axis=0)

array([0.04678594, 0.0661378 , 0.20219419, 0.30055224, 0.37943486,
       0.44461349, 0.72164977, 0.81504301, 0.95919422, 0.97134771])

In [59]:
np.argsort(a, axis=0)

array([4, 8, 7, 5, 1, 2, 3, 6, 9, 0])