In [1]:
# import numpy library.
import numpy as np

In [2]:
!head -n 5 world_alcohol.txt

Year,WHO region,Country,Beverage Types,Display Value
1986,Western Pacific,Viet Nam,Wine,0
1986,Americas,Uruguay,Other,0.5
1985,Africa,Cte d'Ivoire,Wine,1.62
1986,Americas,Colombia,Beer,4.27


In [3]:
# read file from txt file
world_alcohol = np.genfromtxt('world_alcohol.txt', delimiter=',', dtype=str)

In [4]:
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [5]:
# view the ndarray you loaded
print(world_alcohol)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [6]:
# get the help document, if you not familiar the function apis.
print(help(np.genfromtxt))

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
   

In [7]:
# build a 1-dim matrix
vector = np.array([5,4,3,2,1])
print(vector)

[5 4 3 2 1]


In [8]:
# build multi-dims matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# view the ndarray shape
print("vector shape is ", vector.shape)
print("matrix shape is ", matrix.shape)

vector shape is  (5,)
matrix shape is  (3, 3)


In [21]:
# elements of a numpy array must keep same dtype
numbers = np.array([1,2,3,4])
print(numbers.dtype)

numbers = np.array([1,2,3,4.2])
print(numbers.dtype)

numbers = np.array([1,2,3,'string'])
print(numbers.dtype)

int64
float64
<U21


In [22]:
# numpy data selection
world_alcohol[1]

array(['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'], dtype='<U52')

In [31]:
world_alcohol[1, 3]

'Wine'

In [24]:
world_alcohol[0:2]

array([['Year', 'WHO region', 'Country', 'Beverage Types',
        'Display Value'],
       ['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0']], dtype='<U52')

In [29]:
# select the top two rows, column=3 elements
world_alcohol[0:2, 3]

array(['Beverage Types', 'Wine'], dtype='<U52')

In [33]:
# select one column
world_alcohol[:, 3]

array(['Beverage Types', 'Wine', 'Other', 'Wine', 'Beer', 'Beer', 'Other',
       'Wine', 'Spirits', 'Spirits', 'Other', 'Wine', 'Beer', 'Beer',
       'Other', 'Spirits', 'Wine', 'Wine', 'Beer', 'Spirits', 'Beer',
       'Wine', 'Spirits', 'Spirits', 'Beer', 'Other', 'Other', 'Wine',
       'Beer', 'Beer', 'Other', 'Other', 'Wine', 'Beer', 'Other', 'Wine',
       'Spirits', 'Beer', 'Beer', 'Other', 'Spirits', 'Spirits', 'Beer',
       'Spirits', 'Wine', 'Other', 'Beer', 'Spirits', 'Other', 'Beer',
       'Wine', 'Other', 'Beer', 'Wine', 'Beer', 'Spirits', 'Wine', 'Wine',
       'Wine', 'Spirits', 'Other', 'Other', 'Spirits', 'Other', 'Other',
       'Beer', 'Beer', 'Wine', 'Beer', 'Beer', 'Spirits', 'Spirits',
       'Other', 'Other', 'Other', 'Spirits', 'Other', 'Beer', 'Spirits',
       'Other', 'Other', 'Other', 'Wine', 'Spirits', 'Other', 'Other',
       'Wine', 'Wine', 'Wine', 'Beer', 'Wine', 'Wine', 'Beer', 'Spirits',
       'Other', 'Spirits', 'Other', 'Wine', 'Wine', 'Wine', '