In [1]:
import numpy as np

In [2]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
vector = np.arange(15)

In [12]:
vector = vector.reshape((5,3)) # reshape the vector to matrix 5 x 3
print(vector)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [13]:
vector.ndim

2

In [14]:
vector.shape

(5, 3)

In [15]:
vector.dtype.name

'int64'

In [16]:
vector.size

15

In [18]:
np.zeros((3,5),dtype=np.int0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.ones((5,5), dtype=np.int0)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.ones((3,4,5), dtype=np.int0)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [24]:
np.arange(10, 20, 1.5)

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. ])

In [26]:
np.random.random(10).reshape((2,5))

array([[0.06900609, 0.35860012, 0.62822033, 0.31239778, 0.98426232],
       [0.70993467, 0.89386049, 0.39356115, 0.97466852, 0.19176573]])

In [27]:
np.random.random((2,3))

array([[0.25610952, 0.63045599, 0.33132925],
       [0.40697181, 0.08569124, 0.38645995]])

In [29]:
np.linspace(1, 2*np.pi, 100)

array([1.        , 1.05336551, 1.10673102, 1.16009652, 1.21346203,
       1.26682754, 1.32019305, 1.37355856, 1.42692407, 1.48028957,
       1.53365508, 1.58702059, 1.6403861 , 1.69375161, 1.74711711,
       1.80048262, 1.85384813, 1.90721364, 1.96057915, 2.01394465,
       2.06731016, 2.12067567, 2.17404118, 2.22740669, 2.2807722 ,
       2.3341377 , 2.38750321, 2.44086872, 2.49423423, 2.54759974,
       2.60096524, 2.65433075, 2.70769626, 2.76106177, 2.81442728,
       2.86779279, 2.92115829, 2.9745238 , 3.02788931, 3.08125482,
       3.13462033, 3.18798583, 3.24135134, 3.29471685, 3.34808236,
       3.40144787, 3.45481338, 3.50817888, 3.56154439, 3.6149099 ,
       3.66827541, 3.72164092, 3.77500642, 3.82837193, 3.88173744,
       3.93510295, 3.98846846, 4.04183396, 4.09519947, 4.14856498,
       4.20193049, 4.255296  , 4.30866151, 4.36202701, 4.41539252,
       4.46875803, 4.52212354, 4.57548905, 4.62885455, 4.68222006,
       4.73558557, 4.78895108, 4.84231659, 4.8956821 , 4.94904

In [35]:
a = np.random.randint(0,100,size=(3,4))
b = np.array(4)

In [37]:
a

array([[50, 60, 87, 63],
       [91, 97, 83, 38],
       [91, 45, 99, 54]])

In [38]:
b

array(4)

In [39]:
a - b

array([[46, 56, 83, 59],
       [87, 93, 79, 34],
       [87, 41, 95, 50]])

In [41]:
a ** 2

array([[2500, 3600, 7569, 3969],
       [8281, 9409, 6889, 1444],
       [8281, 2025, 9801, 2916]])

In [43]:
a>>1

array([[25, 30, 43, 31],
       [45, 48, 41, 19],
       [45, 22, 49, 27]])

In [53]:
a = np.random.randint(0,10,(3,4))
b = np.random.randint(0,10,(4,3))

In [54]:
np.dot(a, b)

array([[ 38,  59,  47],
       [106,  90, 120],
       [105, 146, 148]])

In [55]:
a.dot(b)

array([[ 38,  59,  47],
       [106,  90, 120],
       [105, 146, 148]])

In [52]:
b = np.random.randint(0,10,(3,4))
a * b

array([[12,  0,  0, 24],
       [ 6,  0, 48,  9],
       [30, 10,  8, 54]])