In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5,19])

In [3]:
# condition caculate
vector == 5

array([False, False, False, False,  True, False])

In [4]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [5]:
matrix == 5

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [6]:
matrix[matrix == 5] # filter with condition

array([5])

In [7]:
matrix[matrix[:, 1] == 5]

array([[4, 5, 6]])

In [8]:
matrix[matrix[:, 1] == 5,:]

array([[4, 5, 6]])

In [9]:
matrix[:,matrix[:, 1] == 5]

array([[2],
       [5],
       [8]])

## multi condation filtering

In [11]:
fitler = (vector == 1) | (vector == 2)
vector[fitler]

array([1, 2])

## modify the dtype of the ndarray

In [16]:
vector = np.array(["1", "2", "3"])
print(vector.dtype)
vector = vector.astype(np.float16)
print(vector.dtype)

<U1
float16


## matrix calculate

In [18]:
print(vector.min(),vector.max(),vector.mean(), vector.std())

1.0 3.0 2.0 0.8164


In [21]:
print(matrix.max(axis=1), matrix.min(axis=1), matrix.mean(axis=1))

[3 6 9] [1 4 7] [2. 5. 8.]


In [22]:
print(matrix.max(axis=0), matrix.min(axis=0), matrix.mean(axis=0))

[7 8 9] [1 2 3] [4. 5. 6.]


In [23]:
matrix.argmin()

0

In [30]:
matrix.min(axis=1)

array([1, 4, 7])

In [24]:
matrix.argmin(axis=1) # return every column min value index

array([0, 0, 0])

In [31]:
matrix.min(axis=0)

array([1, 2, 3])

In [25]:
matrix.argmin(axis=0)

array([0, 0, 0])

In [26]:
matrix.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [27]:
matrix.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [28]:
matrix.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])